# Generated by Django 4.0.4 on 2022-05-07 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_status_novel'),
        ('capitulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='capitulo_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='capitulo_novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='novels.novel', verbose_name='Novel'),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='capitulo_texto',
            field=models.TextField(verbose_name='Texto'),
        ),
    ]
