# Generated by Django 4.0.4 on 2022-05-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capitulos', '0002_alter_capitulo_capitulo_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['capitulo_numero']},
        ),
    ]
