# Generated by Django 4.0.4 on 2022-05-07 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_novel', models.CharField(max_length=120)),
                ('data_novel', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao_novel', models.TextField()),
                ('imagem_novel', models.ImageField(upload_to='novel_img/%Y/%m')),
                ('publicada_novel', models.BooleanField(default=False)),
                ('autor_novel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('categoria_novel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.categoria')),
            ],
        ),
    ]
