# Generated by Django 4.0.4 on 2022-05-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_novel_status_novel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='categoria_novel',
        ),
    ]
